src/eServeSU/Areas/Partner/Controllers/EmployeeController.cs
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using eServeSU.Models;
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;
using System;
using System.Web;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;

namespace eServeSU.Areas.Partner.Controllers
{
    public class EmployeeController : Controller
    {
        private IeServeContext _db;
        private ApplicationUserManager _usrMgr;
        private IAuthenticationManager _authMgr;
        private string _usrID;

        public EmployeeController()
        {
            _db = new eServeContext();
            _usrID = null;
        }


        public EmployeeController(IeServeContext context, string userID)
        {
            _db = context;
            _usrID = userID;
        }

        public string GetUserID
        {
            get
            {
                if (_usrID == null)
                {
                    _usrID = User.Identity.GetUserId();
                }
                return _usrID;
            }
        }
        public ApplicationUserManager UserManager
        {
            get
            {
                if (_usrMgr == null) { _usrMgr = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>(); }
                return _usrMgr;
            }
        }
        public IAuthenticationManager AuthenticationManager
        {
            get
            {
                if (_authMgr == null) { _authMgr = HttpContext.GetOwinContext().Authentication; }
                return _authMgr;
            }
        }

        ////this is for testing as a workaround for Mocking extension methods
        ////the Mock failed return null for GetUserId() (see test commented code)
        //public Func<string> GetUserId; //For testing
        //public EmployeeController()
        //{
        //    GetUserId = () => User.Identity.GetUserId();
        //}

        // return true if the current partner has a valid org profile
        private bool OrganizationProfileExists(string aspNetUser_ID)
        {
            return _db.CommunityPartners.Any(cp => cp.AspNetUser_ID == aspNetUser_ID);
        }


        // GET: Partner/Employee
        [Authorize(Roles = "Partner")]
        public async Task<ActionResult> Index()
        {
            //string myID = User.Identity.GetUserId();
            string myID = GetUserID;

            if (!OrganizationProfileExists(myID))
            {
                this.AddNotification("Please fill out your organization profile before managing employees.",
                    NotificationType.ERROR);
                return RedirectToAction("Profile", "Organization");
            }

            var allRows = await GetAllRows();
            ViewData["row_data"] = JsonConvert.SerializeObject(allRows.Data);
            return View();
        }


        private async Task<JsonResult> GetAllRows()
        {
            //string myID = User.Identity.GetUserId();
            string myID = GetUserID;

            var employees = (await _db.CommunityPartnerStaff
                .Where(cps => cps.CommunityPartner_ID == myID)
                .ToListAsync())
                .Select(e => new {
                    ID = e.ID,
                    TitleFirstLastName = e.TitleFirstLastName,
                    Title = e.Title,
                    FirstName = e.FirstName,
                    LastName = e.LastName,
                    Email = e.Email,
                    Phone = e.Phone
                });
            return Json(employees);
        }

        [Authorize(Roles = "Partner")]
        [OutputCache(Duration = 0, NoStore = true)]
        public async Task<ActionResult> Rows()
        {
            return await GetAllRows();
        }


        // CREATE / EDIT
        // --------------------------------------------------
        // POST: Partner/Employee/CreateUpdate
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Partner")]
        public async Task<ActionResult> CreateUpdate(
            [Bind(Include = "ID, FirstName, LastName, Title, Email, Phone")]
            CommunityPartnerEmployee empl)
        {
            //string partnerID = User.Identity.GetUserId();
            string partnerID = GetUserID;
            empl.CommunityPartner_ID = partnerID;

            // TODO: get the model binder for this to work
            ModelState.Clear();
            TryValidateModel(empl);

            if (!ModelState.IsValid)
            {
                // return errors
                var allErrors = ModelState.Values.SelectMany(v => v.Errors);
                return Json(allErrors);
            }

            // model is valid at this point

            bool is_new_record = empl.ID == 0;

            if (is_new_record)
                _db.CommunityPartnerStaff.Add(empl);
            else
                _db.Entry(empl).State = EntityState.Modified;

            await _db.SaveChangesAsync();

            JsonResult allRows = await GetAllRows();

            return Json(new
            {
                record_inserted = is_new_record,
                record_updated = !is_new_record,
                data_rows = allRows.Data
            });
        }


        // Delete
        // --------------------------------------------------
        // POST: Partner/Employee/Delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Partner")]
        public async Task<ActionResult> Delete([Bind(Include = "ID")] int ID)
        {
            //string partnerID = User.Identity.GetUserId();
            string partnerID = GetUserID;

            var objToRemove = _db.CommunityPartnerStaff
                .Where(cp =>
                    cp.ID == ID &&
                    cp.CommunityPartner_ID == partnerID);

            var result = _db.CommunityPartnerStaff.RemoveRange(objToRemove);

            await _db.SaveChangesAsync();

            JsonResult allRows = await GetAllRows();

            return Json(new {
                record_deleted = true,
                data_rows = allRows.Data
            });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

src/eServeSU/Areas/Partner/Views/Employee/Edit.cshtml
@model eServeSU.Models.CommunityPartnerEmployee

@{
    ViewBag.Title = "Community Partner Employee Profile";
}

<div class="page-header">
    <h2>@ViewBag.Title</h2>
</div>

@if (ViewBag.success != null)
{
    <div class="alert alert-success" role="alert">Successfully updated profile.(employee>edit)</div>
}

@Html.ValidationSummary(true, "", new { @class = "alert alert-danger" })

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
                    }

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

src/eServeSU/Areas/Partner/Views/Employee/EditPartial.cshtml
@model eServeSU.Models.CommunityPartnerEmployee

@{
    Layout = null;
}
@if (ViewBag.success != null)
{
    <div class="alert alert-success" role="alert">Successfully updated profile.(employee>editpartial)</div>
}

<div class="modal-content">

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h2 class="modal-title" id="myModalLabel">
                Employee Details
            </h2>
        </div>
        <div class="modal-body">

            @if (ViewBag.success != null)
            {
                <div class="alert alert-success" role="alert">Successfully updated profile.(edit partial 2)</div>
            }

            <div class="form-horizontal">

                <div class="form-group">
                    @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                    </div>
                </div>


                <div class="form-group">
                    @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
        <div class="modal-footer">

            <button id="empl_delete" type="button" class="btn btn-danger pull-left" data-confirm-container=".modal-content" href="@Url.Action("Delete", new {id = Model.ID})">Delete</button>
            <input type="submit" value="Save" class="btn btn-primary" />
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>

        </div>
    }
    <!-- </Form> -->
</div>

<script>
    $('#empl_delete').popConfirm();

    @{
        if (ViewBag.refreshOnClose != null)
        {
    <text>
    $('body').on('hidden.bs.modal', '.modal', reloadPage);
    </text>
        }
        else
        {
    <text>
    $('body').off('hidden.bs.modal', '.modal', reloadPage);
    </text>
        }
    }
</script>

src/eServeSU/Areas/Partner/Views/Employee/Index.cshtml
@using eServeSU.Models
@model eServeSU.Models.CommunityPartnerEmployee

@{
    ViewBag.Title = "Organization Employees";
}

<!-- Modal box for adding / editing records -->
@Html.Partial("ModalBoxPartial", new CommunityPartnerEmployee())

<div class="page-header">
    <h2>Organization Employees</h2>
</div>

<!-- Alerts from modal actions go here (e.g. record was successfully added)-->
<div id="employee_alerts"></div>


<!-- Employee alert templates -->
<div id="alert_empl_added" class="hidden">
    <div class="alert alert-success alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <strong><span class="glyphicon glyphicon-ok"></span> </strong>
        Employee successfully added. 
    </div>
</div>

<div id="alert_empl_changed" class="hidden">
    <div class="alert alert-success alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <strong><span class="glyphicon glyphicon-ok"></span> </strong>
        Employee successfully modified.
    </div>
</div>

<div id="alert_empl_removed" class="hidden">
    <div class="alert alert-danger alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <strong><span class="glyphicon glyphicon-remove"></span> </strong>
        Employee successfully removed.
    </div>
</div>

<div>
    <a href="#" onclick="clear_modal_form()" data-toggle="modal" data-target="#create_modal" class="btn btn-primary" role="button" style="margin-bottom: 12px">
        Add New Employee
    </a>
</div>

<!-- Mustache row template -->
<script id="rows_template" type="text/html">
    {{#rows}}
    <tr class="clickable-row">
        <td>
            {{TitleFirstLastName}}
        </td>
        <td>
            {{Email}}
        </td>
        <td>
            {{Phone}}
        </td>
    </tr>
    {{/rows}}
</script>


<table id="empl_table" class="table table-striped table-hover">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TitleFirstLastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Phone)
            </th>
        </tr>
    </thead>
    <tbody>
        <!-- Insert Mustache Here -->
    </tbody>
</table>

@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/mustache.js"></script>

    <script>
        // initial row data when page first loads
        data_rows = @Html.Raw(ViewData["row_data"]);
    </script>

    <script src="~/Scripts/EmployeeAjaxScripts.js"></script>
}


src/eServeSU/Areas/Partner/Views/Employee/ModalBoxPartial.cshtml
@model eServeSU.Models.CommunityPartnerEmployee

@{
    Layout = null;
}

<div class="modal fade" id="create_modal" tabindex="-1" role="dialog" aria-labelledby="Create New Employee">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">

            @using (Html.BeginForm("CreateUpdate", "Employee", FormMethod.Post, htmlAttributes: new {id = "modal_form"}))
            {
                @Html.AntiForgeryToken()

                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h2 class="modal-title" id="myModalLabel">
                        Create New Employee
                    </h2>
                </div>
                <div class="modal-body">

                    <div id="create_form_error_well" class="alert alert-danger well-sm" style="display: none">An error occured trying to reach the server</div>

                    <div class="form-horizontal">

                        @Html.HiddenFor(m => m.ID, htmlAttributes: new { data_clear_item = "" })

                        <div class="form-group">
                            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control", data_clear_item = "" } })
                                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger", data_clear_item = "" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control", data_clear_item = "" } })
                                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger", data_clear_item = "" })
                            </div>
                        </div>


                        <div class="form-group">
                            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control", data_clear_item = "" } })
                                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger", data_clear_item = "" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", data_clear_item = "" } })
                                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger", data_clear_item = "" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control", data_clear_item = "" } })
                                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger", data_clear_item = "" })
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">

                    <img id="delete_submit_ajax_loader" src="/Content/Images/ajax-loader-btn.gif" style="display:none" class="pull-left">
                    <a data-delete-link="@Url.Action("Delete")" type="button" id="empl_delete_btn" value="Delete" class="btn btn-danger pull-left" data-confirm-container=".modal-content"> Delete </a>

                    <img id="create_submit_ajax_loader" src="/Content/Images/ajax-loader-btn.gif" style="display:none">
                    <input type="submit" value="Save" class="btn btn-primary" />
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            }
            <!-- </Form> -->
        </div>
    </div>
</div>


<script id="error_template" type="text/html">
    <ul>
        {{#errors}}
        <li>{{ErrorMessage}}</li>
        {{/errors}}
    </ul>
</script>

src/eServeSU/Areas/Partner/Views/Employee/Update.cshtml
@model eServeSU.Models.CommunityPartnerEmployee

@{
    ViewBag.Title = "Community Partner Profile";
}

@if (ViewBag.success != null)
{
    <div class="alert alert-success" role="alert">Successfully updated employee record.(employee>update)</div>
}

<div class="page-header">
    <h2>@ViewBag.Title</h2>
</div>

@Html.ValidationSummary(true, "", new { @class = "alert alert-danger" })

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}