src/eServeSU/Areas/Partner/Models/OpportunityViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using eServeSU.Models;

namespace eServeSU.Areas.Partner.Models
{
    public class OpportunityViewModel
    {
        public OpportunityViewModel(Opportunity opp)
        {
            ID = opp.ID;
            Name = opp.Name;
            Location = opp.Location;
            OpportunityType = opp.Opp_Type.Name;
            DateCreated = opp.DateOfCreation;
            Status = opp.Status;
            Supervisor = opp.CommunityPartnerStaff.TitleFirstLastName;
        }

        public int ID { get; set; }

        public string Name { get; set; }

        public string Location { get; set; }

        [Display(Name = "Opportunity Type")]
        public string OpportunityType { get; set; }

        [Display(Name = "Date Created")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
        public DateTime DateCreated { get; set; }


        public string Status { get; set; }

        public string Supervisor { get; set; }
    }
}

src/eServeSU/Areas/Partner/Controllers/OpportunityController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DocumentFormat.OpenXml.Office2010.CustomUI;
using eServeSU.Areas.Partner.Models;
using eServeSU.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;

namespace eServeSU.Areas.Partner.Controllers
{
    public class OpportunityController : Controller
    {
        private readonly eServeContext _db = new eServeContext();
        private string _usrID;

        public string UserID
        {
            get
            {
                if (_usrID == null)
                {
                    _usrID = User.Identity.GetUserId();
                }
                return _usrID;
            }
        }

        private IEnumerable<SelectListItem> GetAllSupervisors(int? selected = null)
        {
            string myID = User.Identity.GetUserId();
            IEnumerable<SelectListItem> supervisors =
                _db.CommunityPartnerStaff
                .Where(sup => sup.CommunityPartner_ID == myID)
                .ToList()
                .Select(sup => new SelectListItem {
                    Text = sup.TitleFirstLastName,
                    Value = sup.ID.ToString(),
                    Selected = sup.ID == selected
                });
            return supervisors;
        }

        // GET: Partner/Opportunities
        [ExportModelStateToTempData]
        public async Task<ActionResult> Index()
        {
            if (User.IsInRole("Partner"))
                return await IndexPartner();

            if (User.IsInRole("Admin"))
                return await IndexAdmin();

            return RedirectToAction("Index", "Home", new { area = "" });
        }


        // TODO: "PartnerJustApproved"
        private async Task<ActionResult> IndexPartner()
        {
            if (!User.IsInRole("PartnerCanAddOpportunities"))
            {
                if (!_db.CommunityPartners.Any(cp => cp.AspNetUser_ID == UserID))
                {
                    //ModelState.AddModelError("", "Before adding an opportunity, please update your organization's profile.");
                    this.AddNotification("Before adding an opportunity, please update your organization's profile.", NotificationType.ERROR);
                    return RedirectToAction("Profile", "Organization");
                }

                if (User.IsInRole("PartnerPending"))
                {
                    //ModelState.AddModelError("", "Please wait for Admin to approve your profile before adding an opportunity.");
                    this.AddNotification("Please wait for Admin to approve your profile before adding an opportunity.", NotificationType.INFO);
                    return RedirectToAction("Index", "Home", new { area = "" });
                }

                if (User.IsInRole("PartnerRejected"))
                {
                    //ModelState.AddModelError("", "Admin has rejected your profile. Please update your profile and resubmit.");
                    this.AddNotification("Admin has rejected your profile. Please update your profile and resubmit.", NotificationType.ERROR);
                    return RedirectToAction("Profile", "Organization");
                }
            }

            if (!_db.CommunityPartnerStaff.Any(empl => empl.CommunityPartner_ID == UserID))
            {
                //ModelState.AddModelError("", "Before adding an opportunity, please create a profile for at least one employee.");
                this.AddNotification("Before adding an opportunity, please create a profile for at least one employee.", NotificationType.ERROR);
                return RedirectToAction("Index", "Employee");
            }

            var opportunities = (await _db.Opportunities
                .Where(opp => opp.CommunityPartner_ID == UserID)
                .Include(o => o.CommunityPartner)
                .Include(o => o.CommunityPartnerStaff)
                .Include(o => o.Opp_Type)
                .Include(o => o.Univ_Quarter)
                .ToListAsync())
                .Select(opp => new OpportunityViewModel(opp));

            return View("IndexPartner", opportunities);
        }



        private async Task<ActionResult> IndexAdmin()
        {
            IQueryable<Opportunity> opportunities = _db.Opportunities.Include(o => o.CommunityPartner).Include(o => o.CommunityPartnerStaff).Include(o => o.Opp_Type).Include(o => o.Univ_Quarter);

            return View("IndexAdmin", await opportunities.ToListAsync());
        }



        // GET: Partner/Opportunities/Create
        [Authorize(Roles = "PartnerCanAddOpportunities")]
        [ExportModelStateToTempData]
        public ActionResult Create()
        {
            string AspNetUser_ID = User.Identity.GetUserId();

            var userMgr = Request.GetOwinContext().GetUserManager<ApplicationUserManager>();
            var myRoles = userMgr.GetRoles(UserID);
            var cppa = new CommunityPartnerPendingApproval { AspNetUser_ID = UserID };



            Opportunity opp = new Opportunity();

            ViewBag.Type_ID = new SelectList(_db.Opp_Types, "ID", "Name");
            ViewBag.Quarter_ID = new SelectList(_db.Univ_Quarters, "ID", "QuarterName");
            ViewBag.Supervisors = GetAllSupervisors(selected: opp.CommPartnerStaff_ID);
            return View(opp);
        }



        // POST: Partner/Opportunities/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Partner")]
        [ExportModelStateToTempData]
        [ValidateAntiForgeryToken]
        //[ShowAllModelErrors]      // shows all model errors, use for debugging
        public async Task<ActionResult> Create(
            [Bind(Include = "Type_ID, CommPartnerStaff_ID,  Quarter_ID, Name, Location, JobDescription, Requirements, TimeCommittment, TotalNumberOfSlots, OrientationDate, ResumeRequired, MinimumAge, CRCRequiredByPartner, CRCRequiredBySU, LinkToOnlineApp, JobHours, DistanceFromSU")] Opportunity opp)
        {
            opp.CommunityPartner_ID = UserID;

            ModelState.Clear();
            TryValidateModel(opp);

            // INSERT
            if (ModelState.IsValid)
            {
                _db.Opportunities.Add(opp);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");

                // TODO: redirect to record view
            }

            ViewBag.Type_ID = new SelectList(_db.Opp_Types, "ID", "Name", opp.Type_ID);
            ViewBag.Quarter_ID = new SelectList(_db.Univ_Quarters, "ID", "QuarterName", opp.Quarter_ID);
            ViewBag.Supervisors = GetAllSupervisors(selected: opp.CommPartnerStaff_ID);
            return View(opp);
        }

        // GET: Partner/Opportunities/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Opportunity opportunity = await _db.Opportunities.FindAsync(id);
            if (opportunity == null)
            {
                return HttpNotFound();
            }
            return View(opportunity);
        }

        // Get: Partner/Opportunity/DetailsModal/5
        public async Task<ActionResult> DetailsModal(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Opportunity opportunity = await _db.Opportunities.FindAsync(id);
            if (opportunity == null)
            {
                return HttpNotFound();
            }
            return View("DetailsModalPartial", opportunity);
        }

        // GET: Partner/Opportunities/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Opportunity opportunity = await _db.Opportunities.FindAsync(id);
            if (opportunity == null || opportunity.CommunityPartner_ID != User.Identity.GetUserId())
            {
                return HttpNotFound();
            }
            ViewBag.Type_ID = new SelectList(_db.Opp_Types, "ID", "Name", opportunity.Type_ID);
            ViewBag.Quarters = new SelectList(_db.Univ_Quarters, "ID", "QuarterName", opportunity.Quarter_ID);
            ViewBag.Supervisors = GetAllSupervisors(selected: opportunity.CommPartnerStaff_ID);
            return View(opportunity);
        }

        // POST: Partner/Opportunities/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        //[ShowAllModelErrors]      // shows all model errors, use for debugging
        public async Task<ActionResult> Edit(
            [Bind(Include = "ID, Type_ID, CommunityPartner_ID, CommPartnerStaff_ID, Quarter_ID, Name, Location, DateOfCreation, JobDescription, Requirements, TimeCommittment, TotalNumberOfSlots, OrientationDate, Status, ResumeRequired, MinimumAge, CRCRequiredByPartner, CRCRequiredBySU, LinkToOnlineApp, SupervisorEmail, JobHours, DistanceFromSU")]
            [ModelBinder(typeof(UserIdPropertyBinder))]
            Opportunity opportunity)
        {
            if (ModelState.IsValid)
            {

src/eServeSU/Areas/Student/Controllers/OpportunityController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using eServeSU.Areas.Partner.Controllers;
using eServeSU.Models;
using eServeSU.Areas.StudentArea.Models;
using Microsoft.AspNet.Identity;

namespace eServeSU.Areas.StudentArea.Controllers
{
    [Authorize(Roles = "Student")]
    public class OpportunityController : Controller
    {
        private eServeContext _db = new eServeContext();
        private string _usrID;


        public string UserID
        {
            get
            {
                if (_usrID == null) { _usrID = User.Identity.GetUserId(); }
                return _usrID;
            }
            set { _usrID = value; }
        }

        // GET: Student/Opportunity
        [ExportModelStateToTempData]
        public async Task<ActionResult> Index()
        {
            // student requires a profile to register for opportunities
            if (!_db.Students.Any(st => st.AspNetUser_ID == UserID))
            {
                ModelState.AddModelError("", "A student profile is required to register for opportunities");
                return RedirectToAction("Update", "Profile");
            }

            return View();
        }

        // GET: Student/Opportunity/DetailsModal/5
        public async Task<ActionResult> DetailsModal(int? id)
        {

            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            Opportunity opp = await _db.Opportunities.FindAsync(id);
            if (opp == null)
                return new HttpNotFoundResult();

            return View("DetailsModalPartial", opp);
        }

        // AVAILABLE Opportunities
        [ChildActionOnly]
        public ActionResult AvailablePartial()
        {
            var opportunities = _db.Opportunities
                .Where(opp => opp.Students.All(st => st.AspNetUser_ID != UserID))
                .Include(o => o.CommunityPartner)
                .Include(o => o.CommunityPartnerStaff)
                .Include(o => o.Opp_Type)
                .Include(o => o.Univ_Quarter)
                .ToList();

            var oppAvailViewModels = opportunities.Select(opp => new OpportunityRegistrationViewModel(opp));

            return View("AvailableOpportunities", oppAvailViewModels);

        }

        // REGISTERED Opportunities
        [ChildActionOnly]
        public ActionResult RegisteredPartial()
        {
            // TODO: oh dear god, do a performance trace on this monster
            var opportunities = _db.Opportunities
                .Where(opp => opp.Students.Any(st => st.AspNetUser_ID == UserID))
                .Include(o => o.CommunityPartner)
                .Include(o => o.CommunityPartnerStaff)
                .Include(o => o.Opp_Type)
                .Include(o => o.Univ_Quarter)
                .ToList();

            var oppRegViewModels = opportunities.Select(opp => new RegisteredOpportunityViewModel(opp));

            return View("RegisteredOpportunities", oppRegViewModels);
        }


        // POST: Student/Opportunity/SignUp
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> SignUp(
            [Bind(Include = "id")]
            int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            Opportunity opp = await _db.Opportunities.FindAsync(id);
            if (opp == null)
                return new HttpNotFoundResult();

            // insert logic

            Student me = new Student {AspNetUser_ID = UserID};
            _db.Students.Attach(me);
            opp.Students.Add(me);
            _db.SaveChanges();

            return View("ConfirmationModalPartial", opp);
        }



        // GET: Student/Opportunity/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Student/Opportunity/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

    }
}

src/eServeSU/Areas/Student/Views/Opportunity/AvailableOpportunities.cshtml
@model IEnumerable<eServeSU.Areas.StudentArea.Models.OpportunityRegistrationViewModel>

@{
    Layout = null;
}

<div class="page-header">
    <h2>Available Opportunities</h2>
</div>


<!-- Modal Box For Displaying Opportunity Details-->
<div class="modal fade" id="available_modal_box" tabindex="-1" role="dialog" aria-labelledby="PartnerInfo">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content" id="available_modal_content">
            <!-- Content Goes Here -->
        </div>
    </div>
</div>

<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th class="hidden">
                @Html.DisplayNameFor(model => model.ID)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.OpportunityType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Organization)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SlotsAvailable)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DistanceFromSU)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Location)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TimeCommitment)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateCreated)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr class="clickable-row">
                <td class="hidden">
                    @Html.DisplayFor(modelItem => item.ID)
                </td>
                <td>
                    @Html.DisplayFor(model => item.OpportunityType)
                </td>
                <td>
                    @Html.DisplayFor(model => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(model => item.Organization)
                </td>
                <td>
                    @Html.DisplayFor(model => item.SlotsAvailable)
                </td>
                <td>
                    @Html.DisplayFor(model => item.DistanceFromSU)
                </td>
                <td>
                    @Html.DisplayFor(model => item.Location)
                </td>
                <td>
                    @Html.DisplayFor(model => item.TimeCommitment)
                </td>
                <td>
                    @Html.DisplayFor(model => item.DateCreated)
                </td>
                <td>
                    @Html.DisplayFor(model => item.Status)
                </td>
            </tr>
        }
    </tbody>
</table>


@section scripts{

    <!-- Display this while loading-->
    <script id="available_loading_template" type="text/html">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        </div>
        <div class="modal-body">
            <img class="padded-content center-block" src="@Url.Content("~/Content/Images/ajax-loader.gif")">
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
    </script>

    <!-- Display when network error occurs -->
    <script id="available_error_template" type="text/html">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        </div>
        <div class="modal-body">
            <div class="alert alert-danger well-sm">An error occured trying to reach the server</div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
    </script>

    <script>


    </script>


}

src/eServeSU/Areas/Student/Views/Opportunity/ConfirmationModalPartial.cshtml
@model eServeSU.Models.Opportunity
@{
    Layout = null;
}

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <h2>Confirmation</h2>
</div>

<div class="modal-body">
    <div>
        <div class="alert alert-info">Registration is pending until your site supervisor approves your placement</div>

        <div style="margin-top: 20px;">
            <h3>Your next steps</h3>
            <p>
                <ol>
                    <li>Get in touch with site supervisor immediately</li>
                    <li>Attend orientation at your site</li>
                    <li>Commit to a regular schedule of service for the full quarter</li>
                    <li>Complete evaluation at the end of the quarter</li>
                </ol>
            </p>
        </div>

        <div style="margin-top: 20px;">
            <h3>
                @Html.DisplayFor(m => m.Name)
            </h3>
            @Html.DisplayFor(m => m.JobDescription)
        </div>

        <div style="margin-top: 20px;">
            <h3>
                Contact Information
            </h3>
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.CommunityPartnerStaff.TitleFirstLastName)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.CommunityPartnerStaff.TitleFirstLastName)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.CommunityPartnerStaff.Email)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.CommunityPartnerStaff.Email)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.CommunityPartnerStaff.Phone)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.CommunityPartnerStaff.Phone)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.LinkToOnlineApp)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.LinkToOnlineApp)
                </dd>
            </dl>
        </div>
    </div>
</div>

<div class="modal-footer">
    <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
</div>


<script>

    // this is to make sure that the user doesn't accidentally close the modal by clicking outside of it
    $('#modal_box').data('bs.modal').options.backdrop = 'static';
    $('#modal_box').data('bs.modal').options.keyboard = false;
    $('#modal_box').on('hidden.bs.modal', function(e) {
        location.reload(true);
    });


</script>

src/eServeSU/Areas/Student/Views/Opportunity/DetailsModalPartial.cshtml

@model eServeSU.Models.Opportunity
@{
    Layout = null;
}
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <h2>Opportunity Details</h2>
</div>
<div class="modal-body">
    <div>
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Location)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Location)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.DateOfCreation)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.DateOfCreation)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.JobDescription)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.JobDescription)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Requirements)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Requirements)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.TimeCommittment)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.TimeCommittment)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.TotalNumberOfSlots)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.TotalNumberOfSlots)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.OrientationDate)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.OrientationDate)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Status)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Status)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.ResumeRequired)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.ResumeRequired)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.MinimumAge)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.MinimumAge)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.LinkToOnlineApp)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.LinkToOnlineApp)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.JobHours)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.JobHours)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.DistanceFromSU)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.DistanceFromSU)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.CommunityPartner.OrganizationName)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.CommunityPartner.OrganizationName)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.CommunityPartnerStaff.TitleFirstLastName)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.CommunityPartnerStaff.TitleFirstLastName)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Opp_Type.Name)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Opp_Type.Name)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Univ_Quarter.QuarterName)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Univ_Quarter.QuarterName)
            </dd>
        </dl>
    </div>
</div>
<div class="modal-footer">
    <img id="signup_ajax_loader" src="~/Content/Images/ajax-loader-btn.gif" style="display:none">
    <button id="signup-button" type="button" class="btn btn-primary">Sign Up</button>
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
</div>

<!-- Hidden form for signing up -->
@using (Html.BeginForm("SignUp", "Opportunity", FormMethod.Post, new { @id = "signup-form", @class = "hidden" }))
{
    @Html.AntiForgeryToken()
    @Html.Hidden("id", Model.ID);
}

<script>


    // Note: these 2 live in the parent, so no need to re-define them
    // var modal_loading_html = $('#loading_template').html();
    // var modal_error_html = $('#error_template').html();

    $('#signup-button').click(
        function () {

            var form = $('#signup-form');

            $.ajax({
                type: "POST",
                url: form.attr("action"),
                data: form.serialize(),

                beforeSend: function () {
                    $("#signup_ajax_loader").show();
                    $('#modal_box').modal('show');
                },
                complete: function () {
                    $("#signup_ajax_loader").hide();
                },
                error: function () {
                    $('#modal_content').empty().append(modal_error_html);
                    $('#modal_box').modal('show');
                },
                success: function (data) {
                    $('#modal_content').empty().html(data);
                    $('#modal_box').modal('show');
                } // success fn
            }); // anon fn
        }); // click

</script>

src/eServeSU/Areas/Student/Views/Opportunity/Index.cshtml
@model IEnumerable<eServeSU.Models.Student>

@{
    ViewBag.Title = "Student Opportunities";
}

@{
    Html.RenderAction("AvailablePartial", "Opportunity");
    Html.RenderAction("RegisteredPartial", "Opportunity");
}
